/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.dialog;

import bo.StudentBo;
import entity.Account;
import java.util.Locale;
import java.util.ResourceBundle;


public class ViewDetailAccount extends javax.swing.JDialog {

    /**
     * Creates new form ViewDetailAccount
     */
    private final Account account;
    
    //update gui
    private void updateGui(Locale locale) {
        String url = "resource/languages";
        ResourceBundle rb = ResourceBundle.getBundle(url, locale);
        // de doc
        String viewDetail = rb.getString("ViewDetailAccount.ViewDetail");
        String username = rb.getString("ViewDetailAccount.username");
        String type = rb.getString("ViewDetailAccount.type");
        String status = rb.getString("ViewDetailAccount.status");
        String hi = rb.getString("wellcome");


        //update data
        labelLoginAccount7.setText(viewDetail);
        labelLoginAccount11.setText(username);
        labelLoginAccount1.setText(type);
        labelLoginAccount6.setText(status);
        txtHi.setText(hi);
    }

    public ViewDetailAccount(java.awt.Frame parent, boolean modal, Account account, String username, Locale locale) {
        super(parent, modal);
        initComponents();
        this.account = account;
        txtUsername.setText(account.getUserName());
        txtType.setText(account.getType() == 1 ? " Ban" : " Active");
        txtStatus.setText(account.getStatus() == 1 ? " Admin" : "Staff");
        txtHiName.setText(username);
        updateGui(locale);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        labelLoginAccount1 = new javax.swing.JLabel();
        txtHiName = new javax.swing.JLabel();
        labelLoginAccount6 = new javax.swing.JLabel();
        txtType = new javax.swing.JLabel();
        labelLoginAccount7 = new javax.swing.JLabel();
        labelLoginAccount11 = new javax.swing.JLabel();
        txtStatus = new javax.swing.JLabel();
        txtUsername = new javax.swing.JLabel();
        txtHi = new javax.swing.JLabel();
        btnExitt1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("View Detail Account");
        setUndecorated(true);

        kGradientPanel1.setkEndColor(new java.awt.Color(70, 71, 117));
        kGradientPanel1.setkStartColor(new java.awt.Color(70, 71, 117));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelLoginAccount1.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        labelLoginAccount1.setForeground(new java.awt.Color(255, 255, 255));
        labelLoginAccount1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelLoginAccount1.setText("Type:");
        kGradientPanel1.add(labelLoginAccount1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 120, 50));

        txtHiName.setFont(new java.awt.Font("Candara Light", 1, 18)); // NOI18N
        txtHiName.setForeground(new java.awt.Color(255, 255, 255));
        txtHiName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtHiName.setText("------");
        txtHiName.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kGradientPanel1.add(txtHiName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 180, 30));

        labelLoginAccount6.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        labelLoginAccount6.setForeground(new java.awt.Color(255, 255, 255));
        labelLoginAccount6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelLoginAccount6.setText("Status:");
        kGradientPanel1.add(labelLoginAccount6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 120, 50));

        txtType.setFont(new java.awt.Font("Candara Light", 1, 18)); // NOI18N
        txtType.setForeground(new java.awt.Color(255, 255, 255));
        txtType.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtType.setText("_________________");
        kGradientPanel1.add(txtType, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 350, 50));

        labelLoginAccount7.setFont(new java.awt.Font("Calibri Light", 1, 36)); // NOI18N
        labelLoginAccount7.setForeground(new java.awt.Color(255, 255, 255));
        labelLoginAccount7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelLoginAccount7.setText("View Detail Account");
        kGradientPanel1.add(labelLoginAccount7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 350, 50));

        labelLoginAccount11.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        labelLoginAccount11.setForeground(new java.awt.Color(255, 255, 255));
        labelLoginAccount11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelLoginAccount11.setText("Username:");
        kGradientPanel1.add(labelLoginAccount11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 170, 50));

        txtStatus.setFont(new java.awt.Font("Candara Light", 1, 18)); // NOI18N
        txtStatus.setForeground(new java.awt.Color(255, 255, 255));
        txtStatus.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtStatus.setText("________________");
        kGradientPanel1.add(txtStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 400, 50));

        txtUsername.setFont(new java.awt.Font("Candara Light", 1, 18)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(255, 255, 255));
        txtUsername.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtUsername.setText("_________________");
        kGradientPanel1.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 200, 50));

        txtHi.setFont(new java.awt.Font("Candara Light", 1, 18)); // NOI18N
        txtHi.setForeground(new java.awt.Color(255, 255, 255));
        txtHi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtHi.setText("Welcome");
        txtHi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kGradientPanel1.add(txtHi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 30));

        btnExitt1.setFont(new java.awt.Font("Candara Light", 1, 18)); // NOI18N
        btnExitt1.setForeground(new java.awt.Color(255, 255, 255));
        btnExitt1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnExitt1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/close.png"))); // NOI18N
        btnExitt1.setText("X");
        btnExitt1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExitt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitt1MouseClicked(evt);
            }
        });
        kGradientPanel1.add(btnExitt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 20, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitt1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitt1MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnExitt1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnExitt1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel labelLoginAccount1;
    private javax.swing.JLabel labelLoginAccount11;
    private javax.swing.JLabel labelLoginAccount6;
    private javax.swing.JLabel labelLoginAccount7;
    private javax.swing.JLabel txtHi;
    private javax.swing.JLabel txtHiName;
    private javax.swing.JLabel txtStatus;
    private javax.swing.JLabel txtType;
    private javax.swing.JLabel txtUsername;
    // End of variables declaration//GEN-END:variables
}
