/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.dialog;

import bo.StudentBo;
import dao.StudentDao;
import entity.Mark;
import entity.Student;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;
import util.Validate;


public class ViewDetailStudent extends javax.swing.JDialog {

    /**
     * Creates new form ViewDetailBook
     */
    private Student student;
    private final Locale locale;

    private void updateGui(Locale locale) {
        String url = "resource/languages";
        ResourceBundle rb = ResourceBundle.getBundle(url, locale);
        // de doc
        String viewDetail = rb.getString("VietDetailStudent.ViewDetail");
        String exit = rb.getString("ViewDetailAccount.exit");
        String rollNumber = rb.getString("VietDetailStudent.rollNumber");
        String studentName = rb.getString("VietDetailStudent.studentname");
        String email = rb.getString("VietDetailStudent.email");
        String phoneNumber = rb.getString("VietDetailStudent.phoneNumber");
        String address = rb.getString("VietDetailStudent.addresss");
        String remove = rb.getString("VietDetailStudent.remove");
        String update = rb.getString("VietDetailStudent.update");
        String gender = rb.getString("VietDetailStudent.gender");
        String math = rb.getString("VietDetailStudent.Math");
        String literature = rb.getString("VietDetailStudent.Literature");
        String english = rb.getString("VietDetailStudent.English");
        String history = rb.getString("VietDetailStudent.History");
        String mark = rb.getString("VietDetailStudent.Mark");
        String hi = rb.getString("wellcome");

        //update data
        txtTitle.setText(viewDetail);
        btnExit.setText(exit);
        labelLoginAccount11.setText(rollNumber);
        labelLoginAccount4.setText(studentName);
        labelLoginAccount9.setText(email);
        labelLoginAccount10.setText(phoneNumber);
        labelLoginAccount13.setText(address);
        labelLoginAccount8.setText(gender);
        labelMath.setText(math);
        labelLiter.setText(literature);
        labelEnglish.setText(english);
        labelHistory.setText(history);
        labelMark.setText(mark);
        btnRemove.setText(remove);
        btnUpdate.setText(update);
        
        txtHi.setText(hi);
    }

    public ViewDetailStudent(java.awt.Frame parent, boolean modal, Student student, String username, Locale locale, List<Mark> listMark) {
        super(parent, modal);
        initComponents();
        this.locale = locale;
        this.student = student;
        txtHiName.setText(username);
        this.student = student;
        txtFullName.setText(this.student.getFullName());
        txtRollNumber.setText(this.student.getRollNumber());
        if (this.student.isGender()) {
            jRadioButton4.setSelected(true);
        } else {
            jRadioButton3.setSelected(true);
        }
        txtEmail.setText(student.getEmail());
        txtPhoneNumber.setText(student.getPhoneNumber());
        txtAddress.setText(student.getAddress());
        txtMath.setText(listMark.get(0).getMark()+"");
        txtLiter.setText(listMark.get(1).getMark()+"");
        txtEnglish.setText(listMark.get(2).getMark()+"");
        txtHisroty.setText(listMark.get(3).getMark()+"");
        updateGui(locale);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        kGradientPanel4 = new keeptoo.KGradientPanel();
        labelLoginAccount4 = new javax.swing.JLabel();
        txtHiName = new javax.swing.JLabel();
        txtTitle = new javax.swing.JLabel();
        labelLoginAccount11 = new javax.swing.JLabel();
        labelLoginAccount8 = new javax.swing.JLabel();
        labelLoginAccount9 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        btnRemove = new javax.swing.JLabel();
        btnExit = new javax.swing.JLabel();
        txtHi = new javax.swing.JLabel();
        labelLoginAccount10 = new javax.swing.JLabel();
        labelHistory = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JLabel();
        txtPhoneNumber = new javax.swing.JTextField();
        txtFullName = new javax.swing.JTextField();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        labelLoginAccount13 = new javax.swing.JLabel();
        txtRollNumber = new javax.swing.JLabel();
        labelMark = new javax.swing.JLabel();
        labelLiter = new javax.swing.JLabel();
        labelEnglish = new javax.swing.JLabel();
        labelMath = new javax.swing.JLabel();
        txtHisroty = new javax.swing.JTextField();
        txtMath = new javax.swing.JTextField();
        txtLiter = new javax.swing.JTextField();
        txtEnglish = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        kGradientPanel4.setkEndColor(new java.awt.Color(70, 71, 117));
        kGradientPanel4.setkStartColor(new java.awt.Color(70, 71, 117));
        kGradientPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelLoginAccount4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelLoginAccount4.setForeground(new java.awt.Color(255, 255, 255));
        labelLoginAccount4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelLoginAccount4.setText("Full Name:");
        kGradientPanel4.add(labelLoginAccount4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 120, 50));

        txtHiName.setFont(new java.awt.Font("Candara Light", 1, 18)); // NOI18N
        txtHiName.setForeground(new java.awt.Color(255, 255, 255));
        txtHiName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtHiName.setText("---------------");
        txtHiName.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kGradientPanel4.add(txtHiName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 120, 30));

        txtTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtTitle.setForeground(new java.awt.Color(255, 255, 255));
        txtTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtTitle.setText("View Detail Student");
        kGradientPanel4.add(txtTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 250, 50));

        labelLoginAccount11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelLoginAccount11.setForeground(new java.awt.Color(255, 255, 255));
        labelLoginAccount11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelLoginAccount11.setText("Roll Number:");
        kGradientPanel4.add(labelLoginAccount11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 120, 50));

        labelLoginAccount8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelLoginAccount8.setForeground(new java.awt.Color(255, 255, 255));
        labelLoginAccount8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelLoginAccount8.setText("Gender:");
        kGradientPanel4.add(labelLoginAccount8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 120, 50));

        labelLoginAccount9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelLoginAccount9.setForeground(new java.awt.Color(255, 255, 255));
        labelLoginAccount9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelLoginAccount9.setText("Email:");
        kGradientPanel4.add(labelLoginAccount9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 120, 50));

        txtEmail.setBackground(new java.awt.Color(70, 71, 117));
        txtEmail.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(255, 255, 255));
        txtEmail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(240, 240, 240)));
        txtEmail.setCaretColor(new java.awt.Color(240, 240, 240));
        kGradientPanel4.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 370, 40));

        txtAddress.setColumns(20);
        txtAddress.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        txtAddress.setForeground(new java.awt.Color(102, 102, 102));
        txtAddress.setRows(5);
        jScrollPane2.setViewportView(txtAddress);

        kGradientPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 470, 380, 40));

        btnRemove.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRemove.setForeground(new java.awt.Color(255, 255, 255));
        btnRemove.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRemove.setText("Remove");
        btnRemove.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRemove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRemoveMouseClicked(evt);
            }
        });
        kGradientPanel4.add(btnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 700, 90, 30));

        btnExit.setFont(new java.awt.Font("Candara Light", 1, 18)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnExit.setText("Exit");
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });
        kGradientPanel4.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, 50, 30));

        txtHi.setFont(new java.awt.Font("Candara Light", 1, 18)); // NOI18N
        txtHi.setForeground(new java.awt.Color(255, 255, 255));
        txtHi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtHi.setText("Welcome");
        txtHi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kGradientPanel4.add(txtHi, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 90, 30));

        labelLoginAccount10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelLoginAccount10.setForeground(new java.awt.Color(255, 255, 255));
        labelLoginAccount10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelLoginAccount10.setText("Phone Number:");
        kGradientPanel4.add(labelLoginAccount10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 170, 30));

        labelHistory.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelHistory.setForeground(new java.awt.Color(255, 255, 255));
        labelHistory.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelHistory.setText("History :");
        kGradientPanel4.add(labelHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 620, 110, 30));

        btnUpdate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnUpdate.setText("Update");
        btnUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMouseClicked(evt);
            }
        });
        kGradientPanel4.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 700, 100, 30));

        txtPhoneNumber.setBackground(new java.awt.Color(70, 71, 117));
        txtPhoneNumber.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        txtPhoneNumber.setForeground(new java.awt.Color(255, 255, 255));
        txtPhoneNumber.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(240, 240, 240)));
        txtPhoneNumber.setCaretColor(new java.awt.Color(240, 240, 240));
        kGradientPanel4.add(txtPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, 370, 40));

        txtFullName.setBackground(new java.awt.Color(70, 71, 117));
        txtFullName.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        txtFullName.setForeground(new java.awt.Color(255, 255, 255));
        txtFullName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(240, 240, 240)));
        txtFullName.setCaretColor(new java.awt.Color(240, 240, 240));
        kGradientPanel4.add(txtFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 370, 40));

        jRadioButton3.setBackground(new java.awt.Color(70, 71, 117));
        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setForeground(new java.awt.Color(240, 240, 240));
        jRadioButton3.setText("Female");
        kGradientPanel4.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, -1, -1));

        jRadioButton4.setBackground(new java.awt.Color(70, 71, 117));
        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setForeground(new java.awt.Color(240, 240, 240));
        jRadioButton4.setText("Male");
        kGradientPanel4.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, -1, -1));

        labelLoginAccount13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelLoginAccount13.setForeground(new java.awt.Color(255, 255, 255));
        labelLoginAccount13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelLoginAccount13.setText("Address:");
        kGradientPanel4.add(labelLoginAccount13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, 110, 30));

        txtRollNumber.setFont(new java.awt.Font("Candara Light", 1, 18)); // NOI18N
        txtRollNumber.setForeground(new java.awt.Color(255, 255, 255));
        txtRollNumber.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtRollNumber.setText("____________________");
        kGradientPanel4.add(txtRollNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 210, 40));

        labelMark.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelMark.setForeground(new java.awt.Color(255, 255, 255));
        labelMark.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelMark.setText("Mark :");
        kGradientPanel4.add(labelMark, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 580, 110, 30));

        labelLiter.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelLiter.setForeground(new java.awt.Color(255, 255, 255));
        labelLiter.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelLiter.setText("Literature :");
        kGradientPanel4.add(labelLiter, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 620, 110, 30));

        labelEnglish.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelEnglish.setForeground(new java.awt.Color(255, 255, 255));
        labelEnglish.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelEnglish.setText("English :");
        kGradientPanel4.add(labelEnglish, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 580, 80, 30));

        labelMath.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelMath.setForeground(new java.awt.Color(255, 255, 255));
        labelMath.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelMath.setText("Math :");
        kGradientPanel4.add(labelMath, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 580, 110, 30));

        txtHisroty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHisrotyActionPerformed(evt);
            }
        });
        kGradientPanel4.add(txtHisroty, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 620, 80, -1));

        txtMath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMathActionPerformed(evt);
            }
        });
        kGradientPanel4.add(txtMath, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 580, 80, -1));

        txtLiter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLiterActionPerformed(evt);
            }
        });
        kGradientPanel4.add(txtLiter, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 620, 80, -1));

        txtEnglish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnglishActionPerformed(evt);
            }
        });
        kGradientPanel4.add(txtEnglish, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 580, 80, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(kGradientPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 758, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseClicked
        // TODO add your handling code here:
        txtTitle.setText("Update");
        int number = new StudentBo().choiceFunction("Update Student", "Do you want to update student "
                + this.student.getFullName() + " ?", "Yes", "No");

        switch (number) {
            case 0: {
                String name = Validate.getName(txtFullName);
                boolean gender = jRadioButton3.isSelected();
                String email = Validate.getEmail(txtEmail);
                String phoneNumber = Validate.getPhoneNumber(txtPhoneNumber);
                String address = txtAddress.getText();
                int id = this.student.getId();
                Student newStudent = new Student(id, txtRollNumber.getText(), name, gender, email, phoneNumber, address);
                String mess = new StudentBo().update(newStudent, id);
                JOptionPane.showMessageDialog(null, mess);
                this.dispose();
                break;
            }
            case 1: {
                break;
            }
        }
    }//GEN-LAST:event_btnUpdateMouseClicked

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnRemoveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRemoveMouseClicked
        // TODO add your handling code here:
        txtTitle.setText("Remove");
        int choice = new StudentBo().choiceFunction("Question ", "Do you remove student?", "Yes", "No");
        switch (choice) {
            case 0: {
                boolean test = new StudentDao().delete(txtRollNumber.getText());
                if (test) {
                    JOptionPane.showMessageDialog(null, "Remove success");
                } else {
                    JOptionPane.showMessageDialog(null, "Remove Fail");
                }
                this.dispose();
                break;
            }
            case 1: {
                break;
            }
        }
    }//GEN-LAST:event_btnRemoveMouseClicked

    private void txtHisrotyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHisrotyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHisrotyActionPerformed

    private void txtMathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMathActionPerformed

    private void txtLiterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLiterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLiterActionPerformed

    private void txtEnglishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnglishActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnglishActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnExit;
    private javax.swing.JLabel btnRemove;
    private javax.swing.JLabel btnUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane2;
    private keeptoo.KGradientPanel kGradientPanel4;
    private javax.swing.JLabel labelEnglish;
    private javax.swing.JLabel labelHistory;
    private javax.swing.JLabel labelLiter;
    private javax.swing.JLabel labelLoginAccount10;
    private javax.swing.JLabel labelLoginAccount11;
    private javax.swing.JLabel labelLoginAccount13;
    private javax.swing.JLabel labelLoginAccount4;
    private javax.swing.JLabel labelLoginAccount8;
    private javax.swing.JLabel labelLoginAccount9;
    private javax.swing.JLabel labelMark;
    private javax.swing.JLabel labelMath;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEnglish;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JLabel txtHi;
    private javax.swing.JLabel txtHiName;
    private javax.swing.JTextField txtHisroty;
    private javax.swing.JTextField txtLiter;
    private javax.swing.JTextField txtMath;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JLabel txtRollNumber;
    private javax.swing.JLabel txtTitle;
    // End of variables declaration//GEN-END:variables
}
