/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bo.AccountBo;
import bo.StartBo;
import bo.StudentBo;
import dao.AccountDAO;
import dao.StudentDao;
import entity.Account;
import entity.Mark;
import entity.Student;
import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import util.FormController;
import view.dialog.AddStudent;
import view.dialog.ViewDetailAccount;
import view.dialog.ViewDetailStudent;


public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     *
     * @param username
     */
    private final StudentBo studentBo = new StudentBo();
    private Student student = new Student();
    private List<Student> listSearch;
    private List<Student> lists;
    private final Locale locale;
    private final AccountBo accountBo = new AccountBo();
    private final List<Account> listAccount;

    //update gui
    private void updateGui(Locale locale) {
        String url = "resource/languages";
        ResourceBundle rb = ResourceBundle.getBundle(url, locale);
        // de doc
        String home = rb.getString("home.home");
        String showAccount = rb.getString("home.ShowAccount");
        String exit = rb.getString("home.exit");
        String showStudent = rb.getString("home.showStudent");
        String add = rb.getString("home.AddStudent");
        String search = rb.getString("home.Search");
        String searchBy = rb.getString("search.searchBy");
        String key = rb.getString("search.key");
        String hi = rb.getString("wellcome");
        String male = rb.getString("home.male");
        String female = rb.getString("home.Female");
        String total = rb.getString("home.Total");
        String logout = rb.getString("home.logout");

        //update data
        btnHome.setText(home);
        btnShowAccount.setText(showAccount);
        btnShowStudent.setText(showStudent);
        btnSearchStudents.setText(search);
        btnExit.setText(exit);
        btnAddStudent.setText(add);
        labelKey.setText(key);
        labelSearchBy.setText(searchBy);
        btnShowMale.setText(male);
        btnShowFemale.setText(female);
        btnShowAll.setText(total);
        btnLogout.setText(logout);
        txtHi.setText(hi);
    }

    public Home(String username) {
        initComponents();
        resetColor(new JPanel[]{brn_1, brn_2, brn_3, brn_4, brn_5, brn_8, brn_9});
        txtHiName.setText(username);
        jScrollPane1.setVisible(false);
        jScrollPane2.setVisible(false);
        studentBo.hideSomeThings(jComboBox1, txtKey, labelKey, labelSearchButton, labelSearchBy,
                txtFemale, txtMale, txtTotal, btnShowAll, btnShowMale, btnShowFemale);
        // get month and year
        String month = new SimpleDateFormat("MMMMMMMMM").format(Calendar.getInstance().getTime());
        int year = Calendar.getInstance().get(Calendar.YEAR);

        //get day and thu
        Calendar cal = Calendar.getInstance();
        int numberInWeek = cal.get(Calendar.DAY_OF_WEEK);
        String dayInWeek = new StartBo().getMondayToSunday(numberInWeek);
        int dayOfMonth = cal.get(Calendar.DAY_OF_MONTH);
        String day = String.valueOf(dayOfMonth);

        txtYear.setText(dayInWeek + "   " + day + "   " + month + "   " + String.valueOf(year));
        Locale locale = new StartBo().choiceLanguage(student);
        this.locale = locale;
        updateGui(this.locale);
        listAccount = new AccountDAO().getAll();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        side_pane = new javax.swing.JPanel();
        brn_4 = new javax.swing.JPanel();
        btnSearchStudents = new javax.swing.JLabel();
        brn_2 = new javax.swing.JPanel();
        btnShowAccount = new javax.swing.JLabel();
        brn_1 = new javax.swing.JPanel();
        btnHome = new javax.swing.JLabel();
        brn_3 = new javax.swing.JPanel();
        btnShowStudent = new javax.swing.JLabel();
        brn_5 = new javax.swing.JPanel();
        btnAddStudent = new javax.swing.JLabel();
        brn_8 = new javax.swing.JPanel();
        btnExit = new javax.swing.JLabel();
        brn_9 = new javax.swing.JPanel();
        btnLogout = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        labelSearchButton = new javax.swing.JLabel();
        labelSearchBy = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        labelKey = new javax.swing.JLabel();
        txtKey = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtHi = new javax.swing.JLabel();
        txtHiName = new javax.swing.JLabel();
        txtYear = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAccount = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableStudents = new javax.swing.JTable();
        btnShowAll = new javax.swing.JLabel();
        btnShowMale = new javax.swing.JLabel();
        btnShowFemale = new javax.swing.JLabel();
        txtMale = new javax.swing.JLabel();
        txtFemale = new javax.swing.JLabel();
        txtTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        side_pane.setBackground(new java.awt.Color(51, 52, 74));
        side_pane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        brn_4.setBackground(new java.awt.Color(51, 52, 74));

        btnSearchStudents.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSearchStudents.setForeground(new java.awt.Color(255, 255, 255));
        btnSearchStudents.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSearchStudents.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search-3-16.png"))); // NOI18N
        btnSearchStudents.setText("Search Student");
        btnSearchStudents.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearchStudents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchStudentsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout brn_4Layout = new javax.swing.GroupLayout(brn_4);
        brn_4.setLayout(brn_4Layout);
        brn_4Layout.setHorizontalGroup(
            brn_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(brn_4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnSearchStudents, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );
        brn_4Layout.setVerticalGroup(
            brn_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(brn_4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSearchStudents)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        side_pane.add(brn_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 207, 170, 80));

        brn_2.setBackground(new java.awt.Color(51, 52, 74));

        btnShowAccount.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnShowAccount.setForeground(new java.awt.Color(255, 255, 255));
        btnShowAccount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnShowAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/info-16.png"))); // NOI18N
        btnShowAccount.setText("Show Account");
        btnShowAccount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnShowAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnShowAccountMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout brn_2Layout = new javax.swing.GroupLayout(brn_2);
        brn_2.setLayout(brn_2Layout);
        brn_2Layout.setHorizontalGroup(
            brn_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(brn_2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnShowAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );
        brn_2Layout.setVerticalGroup(
            brn_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(brn_2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnShowAccount, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        side_pane.add(brn_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 170, 80));

        brn_1.setBackground(new java.awt.Color(51, 52, 74));

        btnHome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home-5-16.png"))); // NOI18N
        btnHome.setText("Home");
        btnHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout brn_1Layout = new javax.swing.GroupLayout(brn_1);
        brn_1.setLayout(brn_1Layout);
        brn_1Layout.setHorizontalGroup(
            brn_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, brn_1Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        brn_1Layout.setVerticalGroup(
            brn_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(brn_1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnHome)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        side_pane.add(brn_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -3, 170, 70));

        brn_3.setBackground(new java.awt.Color(51, 52, 74));

        btnShowStudent.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnShowStudent.setForeground(new java.awt.Color(255, 255, 255));
        btnShowStudent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnShowStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/info-16.png"))); // NOI18N
        btnShowStudent.setText("Show Student");
        btnShowStudent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnShowStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnShowStudentMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout brn_3Layout = new javax.swing.GroupLayout(brn_3);
        brn_3.setLayout(brn_3Layout);
        brn_3Layout.setHorizontalGroup(
            brn_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(brn_3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnShowStudent, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                .addContainerGap())
        );
        brn_3Layout.setVerticalGroup(
            brn_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(brn_3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnShowStudent)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        side_pane.add(brn_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 137, 170, 70));

        brn_5.setBackground(new java.awt.Color(51, 52, 74));

        btnAddStudent.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAddStudent.setForeground(new java.awt.Color(255, 255, 255));
        btnAddStudent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAddStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add-16.png"))); // NOI18N
        btnAddStudent.setText("Add Student");
        btnAddStudent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddStudentMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout brn_5Layout = new javax.swing.GroupLayout(brn_5);
        brn_5.setLayout(brn_5Layout);
        brn_5Layout.setHorizontalGroup(
            brn_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(brn_5Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(btnAddStudent, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                .addContainerGap())
        );
        brn_5Layout.setVerticalGroup(
            brn_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(brn_5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnAddStudent)
                .addGap(0, 32, Short.MAX_VALUE))
        );

        side_pane.add(brn_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 170, 70));

        brn_8.setBackground(new java.awt.Color(51, 52, 74));

        btnExit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exit-16.png"))); // NOI18N
        btnExit.setText("Exit");
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout brn_8Layout = new javax.swing.GroupLayout(brn_8);
        brn_8.setLayout(brn_8Layout);
        brn_8Layout.setHorizontalGroup(
            brn_8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(brn_8Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        brn_8Layout.setVerticalGroup(
            brn_8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(brn_8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        side_pane.add(brn_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 170, 70));

        brn_9.setBackground(new java.awt.Color(51, 52, 74));

        btnLogout.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout-16.png"))); // NOI18N
        btnLogout.setText("Log out");
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout brn_9Layout = new javax.swing.GroupLayout(brn_9);
        brn_9.setLayout(brn_9Layout);
        brn_9Layout.setHorizontalGroup(
            brn_9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(brn_9Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                .addContainerGap())
        );
        brn_9Layout.setVerticalGroup(
            brn_9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(brn_9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        side_pane.add(brn_9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 170, 70));

        getContentPane().add(side_pane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 170, 490));

        jPanel2.setBackground(new java.awt.Color(70, 71, 117));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelSearchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/icons8_Search_18px.png"))); // NOI18N
        labelSearchButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelSearchButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelSearchButtonMouseClicked(evt);
            }
        });
        jPanel2.add(labelSearchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 30, -1, 20));

        labelSearchBy.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelSearchBy.setForeground(new java.awt.Color(255, 255, 255));
        labelSearchBy.setText("Search by");
        jPanel2.add(labelSearchBy, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 120, -1));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RollNumber", "Name", "All" }));
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 239, 34));

        labelKey.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelKey.setForeground(new java.awt.Color(255, 255, 255));
        labelKey.setText("Enter key:");
        jPanel2.add(labelKey, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 20, 120, -1));

        txtKey.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtKeyMouseClicked(evt);
            }
        });
        jPanel2.add(txtKey, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 20, 313, 31));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/imge_1.jpg"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 60));

        txtHi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtHi.setForeground(new java.awt.Color(255, 255, 255));
        txtHi.setText("Wellcome");
        jPanel2.add(txtHi, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 70, 30));

        txtHiName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtHiName.setForeground(new java.awt.Color(255, 255, 255));
        txtHiName.setText("Admin");
        jPanel2.add(txtHiName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 130, 30));

        txtYear.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtYear.setForeground(new java.awt.Color(255, 255, 255));
        txtYear.setText("Sunday 10 November 2019");
        jPanel2.add(txtYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 170, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 80));

        jPanel1.setBackground(new java.awt.Color(243, 242, 241));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        tableAccount.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tableAccount.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Username", "Type", "Status"
            }
        ));
        tableAccount.setGridColor(new java.awt.Color(255, 255, 255));
        tableAccount.setRowHeight(22);
        tableAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableAccountMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableAccount);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1140, 400));

        jScrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        tableStudents.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tableStudents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Roll Number", "Full Name", "Gender", "Email", "Phone Number", "Address"
            }
        ));
        tableStudents.setGridColor(new java.awt.Color(255, 255, 255));
        tableStudents.setRowHeight(22);
        tableStudents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableStudentsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableStudents);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1140, 400));

        btnShowAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/users-group.png"))); // NOI18N
        btnShowAll.setText("Total:");
        btnShowAll.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnShowAll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnShowAllMouseClicked(evt);
            }
        });
        jPanel1.add(btnShowAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 50, -1, -1));

        btnShowMale.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mars.png"))); // NOI18N
        btnShowMale.setText("Male:");
        btnShowMale.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnShowMale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnShowMaleMouseClicked(evt);
            }
        });
        jPanel1.add(btnShowMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 50, -1, -1));

        btnShowFemale.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/female.png"))); // NOI18N
        btnShowFemale.setText("Female:");
        btnShowFemale.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnShowFemale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnShowFemaleMouseClicked(evt);
            }
        });
        jPanel1.add(btnShowFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 50, -1, -1));

        txtMale.setText("---");
        jPanel1.add(txtMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 50, -1, -1));

        txtFemale.setText("----");
        jPanel1.add(txtFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 50, -1, -1));

        txtTotal.setText("----");
        jPanel1.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 50, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 1140, 490));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    int xx, xy;
    private void txtKeyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtKeyMouseClicked
        // TODO add your handling code here:
        txtKey.setText("");
    }//GEN-LAST:event_txtKeyMouseClicked

    private void labelSearchButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelSearchButtonMouseClicked
        // TODO add your handling code here:
        listSearch = studentBo.showResult(tableStudents, txtKey.getText(),
                jComboBox1.getSelectedIndex(), this.locale);
        studentBo.displayTableStudent(tableStudents, listSearch);
        List<Student>listMale = studentBo.listStudentMale(listSearch);
        txtMale.setText(String.valueOf(listMale.size()));
        int sizeFemale = listSearch.size() - listMale.size();
        txtFemale.setText(String.valueOf(sizeFemale));
        txtTotal.setText(String.valueOf(tableStudents.getRowCount()));
        if (tableStudents.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Not found " + txtKey.getText(), "Message", JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_labelSearchButtonMouseClicked

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
        // TODO add your handling code here:
        studentBo.hideSomeThings(jComboBox1, txtKey, labelKey, labelSearchButton, labelSearchBy,
                txtFemale, txtMale, txtTotal, btnShowAll, btnShowMale, btnShowFemale);
        setColor(brn_1);
        jScrollPane1.setVisible(false);
        jScrollPane2.setVisible(false);
        resetColor(new JPanel[]{brn_2, brn_3, brn_4, brn_5, brn_8, brn_9});
    }//GEN-LAST:event_btnHomeMouseClicked

    private void btnShowAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShowAccountMouseClicked
        // TODO add your handling code here:
        studentBo.hideSomeThings(jComboBox1, txtKey, labelKey,
                labelSearchButton, labelSearchBy,
                txtFemale, txtMale, txtTotal, btnShowAll,
                btnShowMale, btnShowFemale);
        setColor(brn_2);
        jPanel1.setVisible(true);
        jScrollPane1.setVisible(true);
        jScrollPane2.setVisible(false);
        accountBo.displayTableAccount(tableAccount, listAccount);
        resetColor(new JPanel[]{brn_1, brn_3, brn_4, brn_5, brn_8, brn_9});
    }//GEN-LAST:event_btnShowAccountMouseClicked

    private void btnShowStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShowStudentMouseClicked
        // TODO add your handling code here:
        studentBo.hideSomeThings(jComboBox1, txtKey, labelKey,
                labelSearchButton, labelSearchBy);
        studentBo.showSomeThings(txtFemale, txtMale, txtTotal,
                btnShowAll, btnShowMale, btnShowFemale);
        setColor(brn_3);
        jPanel1.setVisible(true);
        jScrollPane2.setVisible(true);
        jScrollPane1.setVisible(false);
        lists = new StudentDao().getAll();
        List<Student>listMale = studentBo.listStudentMale(lists);
        txtMale.setText(String.valueOf(listMale.size()));
        int sizeFemale = lists.size() - listMale.size();
        txtFemale.setText(String.valueOf(sizeFemale));
        txtTotal.setText(String.valueOf(lists.size()));
        studentBo.displayTableStudent(tableStudents, lists);
        resetColor(new JPanel[]{brn_1, brn_2, brn_4, brn_5, brn_8, brn_9});
    }//GEN-LAST:event_btnShowStudentMouseClicked

    private void btnSearchStudentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchStudentsMouseClicked
        // TODO add your handling code here:
        studentBo.removeTable(tableStudents);
        studentBo.showSomeThings(jComboBox1, txtKey, txtFemale,
                txtMale, txtTotal,
                btnShowAll, btnShowMale, btnShowFemale,
                labelSearchBy, labelKey, labelSearchButton);
        setColor(brn_4);
        resetColor(new JPanel[]{brn_1, brn_2, brn_3, brn_5, brn_8, brn_9});
        jPanel1.setVisible(true);
        jScrollPane1.setVisible(false);
        jScrollPane2.setVisible(true);

    }//GEN-LAST:event_btnSearchStudentsMouseClicked

    private void btnAddStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddStudentMouseClicked
        // TODO add your handling code here:      
        studentBo.hideSomeThings(jComboBox1, txtKey,
                labelKey, labelSearchButton, labelSearchBy,
                txtFemale, txtMale, txtTotal, btnShowAll,
                btnShowMale, btnShowFemale);
        setColor(brn_5);
        jScrollPane1.setVisible(false);
        jScrollPane2.setVisible(false);
        resetColor(new JPanel[]{brn_1, brn_2, brn_3, brn_4, brn_8, brn_9});
        FormController.show(new AddStudent(this, true, txtHiName.getText(), this.locale));
    }//GEN-LAST:event_btnAddStudentMouseClicked

    WindowAdapter getAction = new WindowAdapter() {
        @Override
        public void windowClosed(WindowEvent e) {
            new StudentBo().displayTableStudent(tableStudents, new StudentDao().getAll());
            List<Student>listMale = studentBo.listStudentMale(listSearch);
            txtMale.setText(String.valueOf(listMale.size()));
            int sizeFemale = listSearch.size() - listMale.size();
            txtFemale.setText(String.valueOf(sizeFemale));
            txtTotal.setText(String.valueOf(tableStudents.getRowCount()));
        }

    };
    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        // TODO add your handling code here:
        studentBo.hideSomeThings(jComboBox1, txtKey, labelKey, labelSearchButton, labelSearchBy,
                txtFemale, txtMale, txtTotal, btnShowAll, btnShowMale, btnShowFemale);
        setColor(brn_8);
        jScrollPane1.setVisible(false);
        jScrollPane2.setVisible(false);
        resetColor(new JPanel[]{brn_1, brn_2, brn_3, brn_4, brn_5, brn_9});
        int number = studentBo.choiceFunction("Question ",
                "Do you want to close program?", "Yes", "No", "Cancel");
        studentBo.processFunction(this, number);
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
        // TODO add your handling code here:
        studentBo.hideSomeThings(jComboBox1, txtKey, labelKey, labelSearchButton, labelSearchBy,
                txtFemale, txtMale, txtTotal, btnShowAll, btnShowMale, btnShowFemale);
        setColor(brn_9);
        resetColor(new JPanel[]{brn_1, brn_2, brn_3, brn_4, brn_5, brn_8});
        int number = studentBo.choiceFunction("Question ",
                "Do you want to log out?", "Yes", "No");
        switch (number) {
            case 0: {
                FormController.show(new LoginAccount());
                break;
            }
            case 1: {
                break;
            }
        }
    }//GEN-LAST:event_btnLogoutMouseClicked

    private void tableStudentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableStudentsMouseClicked
        // TODO add your handling code here:
        int index = tableStudents.getSelectedRow();
        student = new StudentDao().getAll().get(index);
        List<Mark> listMark = new StudentDao().getMark(student.getId());
        ViewDetailStudent viewDetailStudent = new ViewDetailStudent(this, true, student, txtHiName.getText(), this.locale, listMark);
        viewDetailStudent.addWindowListener(getAction);
        FormController.show(viewDetailStudent);
    }//GEN-LAST:event_tableStudentsMouseClicked

    private void tableAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableAccountMouseClicked
        // TODO add your handling code here:
        int index = tableAccount.getSelectedRow();
        Account au = new AccountDAO().getAll().get(index);
        FormController.show(new ViewDetailAccount(this, true, au,
                txtHiName.getText(), locale));
    }//GEN-LAST:event_tableAccountMouseClicked

    private void btnShowMaleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShowMaleMouseClicked
        // TODO add your handling code here:
        studentBo.removeTable(tableStudents);
        lists = new StudentDao().getAll();
        List<Student>listMale = studentBo.listStudentMale(lists);
        txtMale.setText(String.valueOf(listMale.size()));
        studentBo.displayTableStudent(tableStudents, listMale);
    }//GEN-LAST:event_btnShowMaleMouseClicked

    private void btnShowFemaleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShowFemaleMouseClicked
        // TODO add your handling code here:
        studentBo.removeTable(tableStudents);
        lists = new StudentDao().getAll();
        List<Student>listFemale = studentBo.listStudentFemale(lists);
        txtFemale.setText(String.valueOf(listFemale.size()));
        studentBo.displayTableStudent(tableStudents, listFemale);
    }//GEN-LAST:event_btnShowFemaleMouseClicked

    private void btnShowAllMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShowAllMouseClicked
        // TODO add your handling code here:
        List<Student> lists = new StudentDao().getAll();
        txtTotal.setText(String.valueOf(lists.size()));
        studentBo.displayTableStudent(tableStudents, lists);
    }//GEN-LAST:event_btnShowAllMouseClicked

    private void setColor(JPanel pane) {
        pane.setBackground(new Color(41, 57, 80));
    }

    private void resetColor(JPanel[] pane) {
        for (JPanel pane1 : pane) {
            pane1.setBackground(new Color(23, 35, 51));
        }
    }

    public static void main(String[] args) {
        FormController.show(new Home(" Hang Nguyen"));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel brn_1;
    private javax.swing.JPanel brn_2;
    private javax.swing.JPanel brn_3;
    private javax.swing.JPanel brn_4;
    private javax.swing.JPanel brn_5;
    private javax.swing.JPanel brn_8;
    private javax.swing.JPanel brn_9;
    private javax.swing.JLabel btnAddStudent;
    private javax.swing.JLabel btnExit;
    private javax.swing.JLabel btnHome;
    private javax.swing.JLabel btnLogout;
    private javax.swing.JLabel btnSearchStudents;
    private javax.swing.JLabel btnShowAccount;
    private javax.swing.JLabel btnShowAll;
    private javax.swing.JLabel btnShowFemale;
    private javax.swing.JLabel btnShowMale;
    private javax.swing.JLabel btnShowStudent;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelKey;
    private javax.swing.JLabel labelSearchButton;
    private javax.swing.JLabel labelSearchBy;
    private javax.swing.JPanel side_pane;
    private javax.swing.JTable tableAccount;
    private javax.swing.JTable tableStudents;
    private javax.swing.JLabel txtFemale;
    private javax.swing.JLabel txtHi;
    private javax.swing.JLabel txtHiName;
    private javax.swing.JTextField txtKey;
    private javax.swing.JLabel txtMale;
    private javax.swing.JLabel txtTotal;
    private javax.swing.JLabel txtYear;
    // End of variables declaration//GEN-END:variables
}
