/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bo.AccountBo;
import javax.swing.JOptionPane;
import util.FormController;
import util.Validate;

public class LoginAccount extends javax.swing.JFrame {

    /**
     * Creates new form LoginAccount
     */
    public LoginAccount() {
        initComponents();
        txtPasswordInLogin.setEchoChar('*');
        jPanel4.setVisible(true);
        panelLogin.setVisible(true);
        panelSignUp.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        panelLogin = new keeptoo.KGradientPanel();
        btnLoginInLogin = new javax.swing.JLabel();
        txtUsernameLogin = new javax.swing.JTextField();
        btnClickHere = new javax.swing.JLabel();
        txtRegister = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        labelLoginAccount1 = new javax.swing.JLabel();
        btnExitInLogin = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnSeePasswordInLogin = new javax.swing.JLabel();
        txtPasswordInLogin = new javax.swing.JPasswordField();
        panelSignUp = new keeptoo.KGradientPanel();
        btnLoginInSignUp = new javax.swing.JLabel();
        txtUsername1 = new javax.swing.JTextField();
        txtCPassInSIgnUp = new javax.swing.JPasswordField();
        btnSIgnUpInSignUp = new javax.swing.JLabel();
        labelLoginAccount2 = new javax.swing.JLabel();
        txtPasswordSignUp = new javax.swing.JPasswordField();
        btnExitInSIgnUp = new javax.swing.JLabel();
        btnSmall = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        btnSeeCPassInSignUp = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btnSeePassInSignUp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(70, 71, 117));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Management Student");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Built for developers");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelLogin.setkEndColor(new java.awt.Color(243, 242, 241));
        panelLogin.setkStartColor(new java.awt.Color(243, 242, 241));
        panelLogin.setkTransparentControls(false);

        btnLoginInLogin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnLoginInLogin.setForeground(new java.awt.Color(70, 71, 117));
        btnLoginInLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnLoginInLogin.setText("Login");
        btnLoginInLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLoginInLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginInLoginMouseClicked(evt);
            }
        });

        txtUsernameLogin.setBackground(new java.awt.Color(243, 242, 241));
        txtUsernameLogin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtUsernameLogin.setForeground(new java.awt.Color(70, 71, 117));
        txtUsernameLogin.setText("Username");
        txtUsernameLogin.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(70, 71, 117)));
        txtUsernameLogin.setCaretColor(new java.awt.Color(70, 71, 117));
        txtUsernameLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUsernameLoginMouseClicked(evt);
            }
        });

        btnClickHere.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnClickHere.setForeground(new java.awt.Color(70, 71, 117));
        btnClickHere.setText("Click here");
        btnClickHere.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtRegister.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtRegister.setForeground(new java.awt.Color(70, 71, 117));
        txtRegister.setText("Register now?");
        txtRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtRegisterMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(70, 71, 117));
        jLabel5.setText("Forgot password");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(70, 71, 117));
        jLabel6.setText("New users?");

        labelLoginAccount1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        labelLoginAccount1.setForeground(new java.awt.Color(70, 71, 117));
        labelLoginAccount1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLoginAccount1.setText("Login Account");

        btnExitInLogin.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        btnExitInLogin.setForeground(new java.awt.Color(70, 71, 117));
        btnExitInLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnExitInLogin.setText("X");
        btnExitInLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExitInLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitInLoginMouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(70, 71, 117));

        jLabel3.setBackground(new java.awt.Color(70, 71, 117));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user-32.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(70, 71, 117));

        btnSeePasswordInLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSeePasswordInLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eye-3-24.png"))); // NOI18N
        btnSeePasswordInLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSeePasswordInLoginMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSeePasswordInLoginMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSeePasswordInLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSeePasswordInLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        txtPasswordInLogin.setBackground(new java.awt.Color(240, 240, 240));
        txtPasswordInLogin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPasswordInLogin.setForeground(new java.awt.Color(70, 71, 117));
        txtPasswordInLogin.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtPasswordInLogin.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(70, 71, 117)));
        txtPasswordInLogin.setCaretColor(new java.awt.Color(70, 71, 117));
        txtPasswordInLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPasswordInLoginMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelLoginLayout = new javax.swing.GroupLayout(panelLogin);
        panelLogin.setLayout(panelLoginLayout);
        panelLoginLayout.setHorizontalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLoginLayout.createSequentialGroup()
                        .addGap(510, 510, 510)
                        .addComponent(btnExitInLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelLoginLayout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(labelLoginAccount1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelLoginLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel5)
                        .addGap(144, 144, 144)
                        .addComponent(jLabel6))
                    .addGroup(panelLoginLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(btnClickHere)
                        .addGap(175, 175, 175)
                        .addComponent(txtRegister))
                    .addGroup(panelLoginLayout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(btnLoginInLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelLoginLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPasswordInLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUsernameLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(210, 210, 210))
        );
        panelLoginLayout.setVerticalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(btnExitInLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelLoginLayout.createSequentialGroup()
                        .addComponent(labelLoginAccount1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUsernameLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtPasswordInLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(panelLoginLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel6)))
                .addGap(15, 15, 15)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLoginLayout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addComponent(btnClickHere))
                    .addComponent(txtRegister))
                .addGap(15, 15, 15)
                .addComponent(btnLoginInLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        jPanel4.add(panelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 600));

        panelSignUp.setkEndColor(new java.awt.Color(240, 240, 240));
        panelSignUp.setkStartColor(new java.awt.Color(240, 240, 240));

        btnLoginInSignUp.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnLoginInSignUp.setForeground(new java.awt.Color(70, 71, 117));
        btnLoginInSignUp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnLoginInSignUp.setText("Login");
        btnLoginInSignUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLoginInSignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginInSignUpMouseClicked(evt);
            }
        });

        txtUsername1.setBackground(new java.awt.Color(240, 240, 240));
        txtUsername1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtUsername1.setForeground(new java.awt.Color(70, 71, 117));
        txtUsername1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtUsername1.setText("Username");
        txtUsername1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(70, 71, 117)));
        txtUsername1.setCaretColor(new java.awt.Color(70, 71, 117));
        txtUsername1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUsername1MouseClicked(evt);
            }
        });

        txtCPassInSIgnUp.setBackground(new java.awt.Color(240, 240, 240));
        txtCPassInSIgnUp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCPassInSIgnUp.setForeground(new java.awt.Color(70, 71, 117));
        txtCPassInSIgnUp.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtCPassInSIgnUp.setText("confirmpassword");
        txtCPassInSIgnUp.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(70, 71, 117)));
        txtCPassInSIgnUp.setCaretColor(new java.awt.Color(70, 71, 117));
        txtCPassInSIgnUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCPassInSIgnUpMouseClicked(evt);
            }
        });

        btnSIgnUpInSignUp.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnSIgnUpInSignUp.setForeground(new java.awt.Color(70, 71, 117));
        btnSIgnUpInSignUp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSIgnUpInSignUp.setText("Sign up");
        btnSIgnUpInSignUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSIgnUpInSignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSIgnUpInSignUpMouseClicked(evt);
            }
        });

        labelLoginAccount2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        labelLoginAccount2.setForeground(new java.awt.Color(70, 71, 117));
        labelLoginAccount2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLoginAccount2.setText("Sign Up");

        txtPasswordSignUp.setBackground(new java.awt.Color(240, 240, 240));
        txtPasswordSignUp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPasswordSignUp.setForeground(new java.awt.Color(70, 71, 117));
        txtPasswordSignUp.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtPasswordSignUp.setText("Password");
        txtPasswordSignUp.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(70, 71, 117)));
        txtPasswordSignUp.setCaretColor(new java.awt.Color(70, 71, 117));
        txtPasswordSignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPasswordSignUpMouseClicked(evt);
            }
        });

        btnExitInSIgnUp.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        btnExitInSIgnUp.setForeground(new java.awt.Color(70, 71, 117));
        btnExitInSIgnUp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnExitInSIgnUp.setText("X");
        btnExitInSIgnUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExitInSIgnUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitInSIgnUpMouseClicked(evt);
            }
        });

        btnSmall.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        btnSmall.setForeground(new java.awt.Color(70, 71, 117));
        btnSmall.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSmall.setText("_");
        btnSmall.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSmall.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSmallMouseClicked(evt);
            }
        });

        jPanel7.setBackground(new java.awt.Color(70, 71, 117));

        btnSeeCPassInSignUp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSeeCPassInSignUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eye-3-24.png"))); // NOI18N
        btnSeeCPassInSignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSeeCPassInSignUpMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSeeCPassInSignUpMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(btnSeeCPassInSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSeeCPassInSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel5.setBackground(new java.awt.Color(70, 71, 117));

        jLabel10.setBackground(new java.awt.Color(70, 71, 117));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user-32.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel10))
        );

        jPanel6.setBackground(new java.awt.Color(70, 71, 117));

        btnSeePassInSignUp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSeePassInSignUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eye-3-24.png"))); // NOI18N
        btnSeePassInSignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSeePassInSignUpMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSeePassInSignUpMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(btnSeePassInSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSeePassInSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout panelSignUpLayout = new javax.swing.GroupLayout(panelSignUp);
        panelSignUp.setLayout(panelSignUpLayout);
        panelSignUpLayout.setHorizontalGroup(
            panelSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSignUpLayout.createSequentialGroup()
                .addGroup(panelSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSignUpLayout.createSequentialGroup()
                        .addGap(460, 460, 460)
                        .addComponent(btnSmall, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelSignUpLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(labelLoginAccount2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelSignUpLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(txtCPassInSIgnUp, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelSignUpLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(txtUsername1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelSignUpLayout.createSequentialGroup()
                        .addGap(490, 490, 490)
                        .addComponent(btnExitInSIgnUp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelSignUpLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(txtPasswordSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelSignUpLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnLoginInSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSIgnUpInSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );
        panelSignUpLayout.setVerticalGroup(
            panelSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSignUpLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panelSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExitInSIgnUp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelSignUpLayout.createSequentialGroup()
                        .addGroup(panelSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelSignUpLayout.createSequentialGroup()
                                .addComponent(btnSmall, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(labelLoginAccount2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtUsername1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(panelSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPasswordSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(panelSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelSignUpLayout.createSequentialGroup()
                                .addComponent(txtCPassInSIgnUp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(99, 99, 99)
                                .addGroup(panelSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnLoginInSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSIgnUpInSignUp)))
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(119, 119, 119))
        );

        jPanel4.add(panelSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 600));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 540, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginInLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginInLoginMouseClicked
        // TODO add your handling code here:
        String name = txtUsernameLogin.getText();
        String password = txtPasswordInLogin.getText();
        String mess = new AccountBo().signInAccount(name, password);
        JOptionPane.showMessageDialog(this, mess, "Message ", JOptionPane.PLAIN_MESSAGE);
        if (mess.equalsIgnoreCase("Login successful")) {
            String username = name.toUpperCase();
            FormController.show(new Home(username));
            this.dispose();
        }
    }//GEN-LAST:event_btnLoginInLoginMouseClicked

    private void txtUsernameLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsernameLoginMouseClicked
        // TODO add your handling code here:
        jPanel4.setVisible(true);
        panelLogin.setVisible(true);
        panelSignUp.setVisible(false);
        txtUsernameLogin.setText("");
    }//GEN-LAST:event_txtUsernameLoginMouseClicked

    private void txtRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRegisterMouseClicked
        // TODO add your handling code here:
        jPanel4.setVisible(true);
        panelSignUp.setVisible(true);
        panelLogin.setVisible(false);
        txtCPassInSIgnUp.setText("ConfimPassword");
        txtPasswordSignUp.setText("Password");
        txtCPassInSIgnUp.setEchoChar((char) 0);
        txtPasswordSignUp.setEchoChar((char) 0);
    }//GEN-LAST:event_txtRegisterMouseClicked

    private void btnExitInLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitInLoginMouseClicked
        // TODO add your handling code here:
        jPanel4.setVisible(true);
        panelSignUp.setVisible(false);
        panelLogin.setVisible(true);
        System.exit(0);
    }//GEN-LAST:event_btnExitInLoginMouseClicked

    private void btnSeePasswordInLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSeePasswordInLoginMouseClicked
        // TODO add your handling code here:
        jPanel4.setVisible(true);
        panelSignUp.setVisible(false);
        panelLogin.setVisible(true);
        txtPasswordInLogin.setEchoChar((char) 0);
    }//GEN-LAST:event_btnSeePasswordInLoginMouseClicked

    private void btnSeePasswordInLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSeePasswordInLoginMouseExited
        // TODO add your handling code here:
        jPanel4.setVisible(true);
        panelSignUp.setVisible(false);
        panelLogin.setVisible(true);
        txtPasswordInLogin.setEchoChar('*');
    }//GEN-LAST:event_btnSeePasswordInLoginMouseExited

    private void btnLoginInSignUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginInSignUpMouseClicked
        // TODO add your handling code here:
        jPanel4.setVisible(true);
        panelSignUp.setVisible(false);
        panelLogin.setVisible(true);
        txtPasswordSignUp.setEchoChar((char) 0);
        txtCPassInSIgnUp.setEchoChar((char) 0);
    }//GEN-LAST:event_btnLoginInSignUpMouseClicked

    private void txtUsername1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsername1MouseClicked
        // TODO add your handling code here:
        jPanel4.setVisible(true);
        panelSignUp.setVisible(true);
        panelLogin.setVisible(false);
        txtUsernameLogin.setText("");
    }//GEN-LAST:event_txtUsername1MouseClicked

    private void txtCPassInSIgnUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCPassInSIgnUpMouseClicked
        // TODO add your handling code here:
        jPanel4.setVisible(true);
        panelSignUp.setVisible(true);
        panelLogin.setVisible(false);
        txtCPassInSIgnUp.setText("");
    }//GEN-LAST:event_txtCPassInSIgnUpMouseClicked

    private void btnSIgnUpInSignUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSIgnUpInSignUpMouseClicked
        // TODO add your handling code here:
        jPanel4.setVisible(true);
        panelLogin.setVisible(false);
        panelSignUp.setVisible(true);
        String name = Validate.getName(txtUsernameLogin);
        String password = Validate.getPassword(txtPasswordSignUp);
        String cPassword = txtCPassInSIgnUp.getText();
        String mess = new AccountBo().signUp(name, password, cPassword);
        JOptionPane.showMessageDialog(this, mess, "Message", JOptionPane.PLAIN_MESSAGE);
        if (mess.equalsIgnoreCase("Sign Up successful")) {
            String username = name.toUpperCase();
            FormController.show(new Home(username));
            this.dispose();
        }
    }//GEN-LAST:event_btnSIgnUpInSignUpMouseClicked

    private void txtPasswordSignUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPasswordSignUpMouseClicked
        // TODO add your handling code here: 
        jPanel4.setVisible(true);
        panelSignUp.setVisible(true);
        panelLogin.setVisible(false);
        txtPasswordSignUp.setText("");
    }//GEN-LAST:event_txtPasswordSignUpMouseClicked

    private void btnExitInSIgnUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitInSIgnUpMouseClicked
        // TODO add your handling code here:
        jPanel4.setVisible(true);
        panelSignUp.setVisible(true);
        panelLogin.setVisible(false);
        System.exit(0);
    }//GEN-LAST:event_btnExitInSIgnUpMouseClicked

    private void btnSmallMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSmallMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSmallMouseClicked

    private void btnSeePassInSignUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSeePassInSignUpMouseClicked
        // TODO add your handling code here:
        jPanel4.setVisible(true);
        panelSignUp.setVisible(true);
        panelLogin.setVisible(false);
        txtPasswordSignUp.setEchoChar((char) 0);
    }//GEN-LAST:event_btnSeePassInSignUpMouseClicked

    private void btnSeePassInSignUpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSeePassInSignUpMouseExited
        // TODO add your handling code here:
        jPanel4.setVisible(true);
        panelSignUp.setVisible(true);
        panelLogin.setVisible(false);
        txtPasswordSignUp.setEchoChar('*');
    }//GEN-LAST:event_btnSeePassInSignUpMouseExited

    private void txtPasswordInLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPasswordInLoginMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordInLoginMouseClicked

    private void btnSeeCPassInSignUpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSeeCPassInSignUpMouseExited
        // TODO add your handling code here:
        jPanel4.setVisible(true);
        panelSignUp.setVisible(true);
        panelLogin.setVisible(false);
        txtCPassInSIgnUp.setEchoChar('*');
    }//GEN-LAST:event_btnSeeCPassInSignUpMouseExited

    private void btnSeeCPassInSignUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSeeCPassInSignUpMouseClicked
        // TODO add your handling code here:
        jPanel4.setVisible(true);
        panelSignUp.setVisible(true);
        panelLogin.setVisible(false);
        txtCPassInSIgnUp.setEchoChar((char) 0);
    }//GEN-LAST:event_btnSeeCPassInSignUpMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FormController.show(new LoginAccount());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnClickHere;
    private javax.swing.JLabel btnExitInLogin;
    private javax.swing.JLabel btnExitInSIgnUp;
    private javax.swing.JLabel btnLoginInLogin;
    private javax.swing.JLabel btnLoginInSignUp;
    private javax.swing.JLabel btnSIgnUpInSignUp;
    private javax.swing.JLabel btnSeeCPassInSignUp;
    private javax.swing.JLabel btnSeePassInSignUp;
    private javax.swing.JLabel btnSeePasswordInLogin;
    private javax.swing.JLabel btnSmall;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel labelLoginAccount1;
    private javax.swing.JLabel labelLoginAccount2;
    private keeptoo.KGradientPanel panelLogin;
    private keeptoo.KGradientPanel panelSignUp;
    private javax.swing.JPasswordField txtCPassInSIgnUp;
    private javax.swing.JPasswordField txtPasswordInLogin;
    private javax.swing.JPasswordField txtPasswordSignUp;
    private javax.swing.JLabel txtRegister;
    private javax.swing.JTextField txtUsername1;
    private javax.swing.JTextField txtUsernameLogin;
    // End of variables declaration//GEN-END:variables
}
